version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: lms_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lms
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lms_backend
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: lms
    ports:
      - "3000:3000"
    networks:
      - lms_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lms_frontend
    ports:
      - "4000:4000"
    networks:
      - lms_network

volumes:
  db_data:

networks:
  lms_network:
    driver: bridge
